package CrudClientes;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Eric Rocha
 */


public class CadastrarCliente extends javax.swing.JInternalFrame {


    /**
     * Creates new form ConsultaCliente
     * 
     */
    
    
    
    int idAlteracao=0;
    public String caminhoimagem = "";
    public String cpfcnpj = "";
    public CadastrarCliente() {
            initComponents();
    }
    
    public CadastrarCliente(int idAlteracao) {
        initComponents();
        this.idAlteracao = idAlteracao;
        try{
            //Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","admin");
            Connection con = DriverManager.getConnection("jdbc:mysql://mysql5014.site4now.net:3306/db_a464fd_realdev?zeroDateTimeBehavior=convertToNull","a464fd_realdev","nq1u2hi1");

            String sql = "select * from javaclientes where id = ? ";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setInt(1, idAlteracao);
            ResultSet rs = stmt.executeQuery();
            while(rs.next()){

                txtNome.setText(rs.getString("nome"));
                txtTelefone.setText(rs.getString("tel"));
                txtEmail.setText(rs.getString("email"));
                cpfcnpj = rs.getString("cpf_cnpj");
                if(cpfcnpj.length() == 14){
                    txtCPF.setText(cpfcnpj);
                }else{
                    if(cpfcnpj.length() == 18){
                        txtCNPJ.setText(cpfcnpj);
                        //this.jCheckBox2.setSelected(true);
                    }
                }
                
                //txtCPF.setText(rs.getString("cpf_cnpj"));
                txtEndereco.setText(rs.getString("endereco"));
                txtNum.setText(rs.getString("numero"));
                txtComp.setText(rs.getString("comp"));
                txtBairro.setText(rs.getString("bairro"));
                txtCEP.setText(rs.getString("cep"));
                txtCidade.setText(rs.getString("cidade"));
                txtEstado.setText(rs.getString("estado"));
                txtObs.setText(rs.getString("obs"));
                String caminho = rs.getString("img");
                ImageIcon imagem = new ImageIcon(caminho);
                jLabelImagem.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(150, 200, Image.SCALE_DEFAULT)));
           
            }
            stmt.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro durante o cadastro.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jButtonImagem = new javax.swing.JButton();
        jLabelImagem = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabelObrigatorioNome = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        txtCPF = new javax.swing.JFormattedTextField();
        txtCNPJ = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtComp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCidade = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        txtCEP = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setForeground(java.awt.Color.white);
        setTitle("Cadastrar Cliente");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/CrudClientes/logo.png"))); // NOI18N

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome/Razão Social*:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, -1, 20));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 33, 205, 20));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Telefone:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 52, 20));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Email:");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 52, 20));

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 99, 205, 20));

        jButtonImagem.setText("Adicionar imagem");
        jButtonImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImagemActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 236, -1, -1));

        jLabelImagem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 30, 150, 200));

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 66, 205, 20));

        jButton1.setText("Remover imagem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 265, -1, -1));

        jLabelObrigatorioNome.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabelObrigatorioNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 33, 100, 20));
        jLabelObrigatorioNome.setVisible(false);

        jCheckBox1.setText("CPF:");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jCheckBox1FocusLost(evt);
            }
        });
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, 52, 20));
        //this.jCheckBox1.setSelected(true);

        jCheckBox2.setText("CNPJ:");
        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, -1, 20));

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 132, 205, 20));
        this.txtCPF.enable(false);

        try {
            txtCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCNPJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 165, 205, 20));
        this.txtCNPJ.enable(false);

        jTabbedPane3.addTab("Dados", jPanel1);

        jLabel1.setText("Endereço:");

        jLabel6.setText("Número:");

        txtNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumActionPerformed(evt);
            }
        });

        jLabel7.setText("Complemento:");

        jLabel8.setText("Bairro:");

        jLabel9.setText("CEP:");

        jLabel10.setText("Cidade:");

        jLabel11.setText("Estado:");

        try {
            txtCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCEP, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(txtComp)
                    .addComponent(txtEndereco)
                    .addComponent(txtNum)
                    .addComponent(txtBairro))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstado)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Endereço", jPanel2);

        jLabel12.setText("Observações:");

        txtObs.setColumns(20);
        txtObs.setRows(5);
        jScrollPane1.setViewportView(txtObs);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Observações", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btCancelar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

     
        String controle = this.txtCPF.getText();
        controle = controle.replaceAll(" ","");
        if(controle.length() > 4){
            cpfcnpj = this.txtCPF.getText();
        }else{
            controle = this.txtCNPJ.getText();
            controle = controle.replaceAll(" ","");
            if(controle.length() > 5){
                 cpfcnpj = this.txtCNPJ.getText();
            }   
        }
        
        String valnome = this.txtNome.getText();
        if (valnome.length() > 0) {
            jLabelObrigatorioNome.setVisible(false);
            if ((valnome.length() > 1) && (valnome.length() < 5)) {
                jLabelObrigatorioNome.setVisible(true);
                jLabelObrigatorioNome.setText("Muito curto!");
            } else {
                jLabelObrigatorioNome.setVisible(false);
            }
        } else {
            jLabelObrigatorioNome.setVisible(true);
            jLabelObrigatorioNome.setText("Obrigatorio!");
        }
        if ( this.txtNome.getText().length()>5 ){
            try{
                if(idAlteracao == 0){ 
                    Connection con = DriverManager.getConnection("jdbc:mysql://mysql5014.site4now.net:3306/db_a464fd_realdev?zeroDateTimeBehavior=convertToNull","a464fd_realdev","nq1u2hi1");

                    String sql = "insert into javaclientes(nome,tel,email,cpf_cnpj,endereco,numero,comp,bairro,cep,cidade,estado,obs,img) values (?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement stmt = con.prepareStatement(sql);
                    stmt.setString(1, this.txtNome.getText());
                    stmt.setString(2, this.txtTelefone.getText());
                    stmt.setString(3, this.txtEmail.getText()); 
                    stmt.setString(4, this.cpfcnpj);
                    stmt.setString(5, this.txtEndereco.getText());
                    stmt.setString(6, this.txtNum.getText());
                    stmt.setString(7, this.txtComp.getText());
                    stmt.setString(8, this.txtBairro.getText());
                    stmt.setString(9, this.txtCEP.getText());
                    stmt.setString(10, this.txtCidade.getText());
                    stmt.setString(11, this.txtEstado.getText());
                    stmt.setString(12, this.txtObs.getText());
                    if(caminhoimagem.length() > 0){
                      stmt.setString(13, caminhoimagem);
                    }else{
                       stmt.setString(13, "");  
                    }

                    stmt.execute();
                    stmt.close();
                    con.close();
                }else{
                    Connection con = DriverManager.getConnection("jdbc:mysql://mysql5014.site4now.net:3306/db_a464fd_realdev?zeroDateTimeBehavior=convertToNull","a464fd_realdev","nq1u2hi1");

                    String sql = "update javaclientes set nome=?,tel=?,email=?,cpf_cnpj=?,endereco=?, numero=?, comp=?,bairro=?,cep=?,cidade=?,estado=?, obs=?, img=? where id = ?";
                    PreparedStatement stmt = con.prepareStatement(sql);
                    stmt.setString(1, this.txtNome.getText());
                    stmt.setString(2, this.txtTelefone.getText());
                    stmt.setString(3, this.txtEmail.getText());
                    stmt.setString(4, this.cpfcnpj);
                    stmt.setString(5, this.txtEndereco.getText());
                    stmt.setString(6, this.txtNum.getText());
                    stmt.setString(7, this.txtComp.getText());
                    stmt.setString(8, this.txtBairro.getText());
                    stmt.setString(9, this.txtCEP.getText());
                    stmt.setString(10, this.txtCidade.getText());
                    stmt.setString(11, this.txtEstado.getText());
                    stmt.setString(12, this.txtObs.getText());
                    if(caminhoimagem.length() > 0){
                       stmt.setString(13, caminhoimagem);
                    }else{
                       stmt.setString(13, "");  
                    }
                    stmt.setInt(14, idAlteracao);
                    stmt.execute();
                    stmt.close();
                    con.close();
                }
                JOptionPane.showMessageDialog(this, "Cliente Cadastrado com Sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, "Ocorreu um erro durante o cadastro.", "Erro", JOptionPane.ERROR_MESSAGE);
        } 
            
        } else {
            JOptionPane.showMessageDialog(this, "Confira os campos Obrigatórios!!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }

            
        
        
        
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    
        public byte[] converterArquivo(File file) throws Exception {
        FileInputStream fis = new FileInputStream(file);
        ByteArrayOutputStream baos = new ByteArrayOutputStream();

        byte[] buffer = new byte[25600];
        int bytesRead = 0;

        while ((bytesRead = fis.read(buffer, 0, buffer.length)) != -1) {
            baos.write(buffer, 0, bytesRead);
        }
        return baos.toByteArray();
        }
        
    
    private void txtNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumActionPerformed
       
    }//GEN-LAST:event_txtNumActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected()){
            this.txtCNPJ.enable(true);
            this.jCheckBox1.setSelected(false);
            this.txtCPF.enable(false);
            this.txtCPF.setText("");

        }else{
            this.txtCNPJ.enable(false);
            this.txtCNPJ.setText("");

        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected()){
            this.txtCPF.enable(true);
            this.txtCNPJ.enable(false);
            this.jCheckBox2.setSelected(false);
            this.txtCNPJ.setText("");
        }else{
            this.txtCPF.enable(false);
            this.txtCPF.setText("");
            /*String strOrigem = "Luiz                Inácio                Lula                      da           Silva";
            strOrigem = strOrigem.replaceAll(" ","");
            System.out.println(strOrigem);*/

        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jCheckBox1FocusLost

    }//GEN-LAST:event_jCheckBox1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jLabelImagem.setIcon(null);
        caminhoimagem = "";
        JOptionPane.showMessageDialog(this, "Imagem removida.", "Imagem removida", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImagemActionPerformed
        BufferedImage imgfile = null;
        JFileChooser foto = new JFileChooser();
        foto.setDialogTitle("Selecione uma imagem");
        foto.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int opc = foto.showOpenDialog(this);
        if(opc == JFileChooser.APPROVE_OPTION){
            File file = new File("Caminho");
            file = foto.getSelectedFile(); //recebe caminho
            String filename = file.getAbsolutePath();

            ImageIcon imagem = new ImageIcon(foto.getSelectedFile().getPath());
            jLabelImagem.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(jLabelImagem.getWidth(), jLabelImagem.getHeight(), Image.SCALE_DEFAULT)));

            Calendar c = Calendar.getInstance();
            int ano = c.get(Calendar.YEAR);
            int mes = c.get(Calendar.MONTH);
            int dia = c.get(Calendar.DAY_OF_MONTH);
            int hora = c.get(Calendar.HOUR_OF_DAY);
            int minuto = c.get(Calendar.MINUTE);
            int segudo = c.get(Calendar.SECOND);
            int milesimo = c.get(Calendar.MILLISECOND);

            String nomecompleto = hora + "-" + minuto + "-" + segudo + "-" + milesimo + "-" + ano + "-" + mes + "-" + dia;
            File diretorio = new File("C:\\Users\\Public\\Pictures\\CadastroCrud");
            diretorio.mkdir();

            try {
                imgfile = ImageIO.read(file);
                ImageIO.write(imgfile, "jpg",new File("C:\\Users\\Public\\Pictures\\CadastroCrud\\"+nomecompleto+".jpg"));
                    caminhoimagem = "C:\\Users\\Public\\Pictures\\CadastroCrud\\"+nomecompleto+".jpg";
                } catch (IOException ex) {
                    //Logger.getLogger(CadastrarCliente.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(this, "Ocorreu um erro ao gravar a imagem.", "Erro", JOptionPane.ERROR_MESSAGE);
                }

            }
    }//GEN-LAST:event_jButtonImagemActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed

    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed

    }//GEN-LAST:event_txtNomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonImagem;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelObrigatorioNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCEP;
    private javax.swing.JFormattedTextField txtCNPJ;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNum;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
